# Generated by Django 4.1 on 2022-08-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='your_hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_MBTI', models.CharField(max_length=4)),
                ('first_point', models.IntegerField()),
                ('second_point', models.IntegerField()),
                ('third_point', models.IntegerField()),
            ],
        ),
    ]
