# Generated by Django 4.1 on 2022-08-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_hobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='your_hobby',
            name='return_hobby',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='your_hobby',
            name='first_point',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='your_hobby',
            name='second_point',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='your_hobby',
            name='third_point',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='your_hobby',
            name='your_MBTI',
            field=models.CharField(default='', max_length=4),
        ),
    ]
