# Generated by Django 4.1 on 2022-08-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_hobby', '0002_your_hobby_return_hobby_alter_your_hobby_first_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='your_hobby',
            name='hobby_category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
